"""Version data — single point of truth updated by the release process.

This file contains *only* the version string and release highlights.
It is regenerated by ``generate_db.bat`` during release — do not edit
the data here by hand; instead update ``CHANGELOG.md`` and run the
release script.

Usage (always import via the public ``src.version`` module)::

    from src.version import __version__, get_release_highlights

"""

from __future__ import annotations

__version__ = "0.2.5"

# ------------------------------------------------------------------
# Release highlights — user-facing feature summaries per version
# ------------------------------------------------------------------

_RELEASE_HIGHLIGHTS: dict[str, dict[str, tuple[str, ...]]] = {
    "0.2.5": {
        "修复": (
            "标签面板分区联动: 切换分区时标签管理面板已同步刷新，标签列表、重命名、合并均限定在当前分区范围内",
        ),
    },
}
