"""Version data — single point of truth updated by the release process.

This file contains *only* the version string and release highlights.
It is regenerated by ``generate_db.bat`` during release — do not edit
the data here by hand; instead update ``CHANGELOG.md`` and run the
release script.

Usage (always import via the public ``src.version`` module)::

    from src.version import __version__, get_release_highlights

"""

from __future__ import annotations

__version__ = "0.2.5"

# ------------------------------------------------------------------
# Release highlights — user-facing feature summaries per version
# ------------------------------------------------------------------

_RELEASE_HIGHLIGHTS: dict[str, dict[str, tuple[str, ...]]] = {
    "0.2.5": {
        "修复": (
            "标签面板分区联动: 切换分区时标签管理面板已同步刷新，标签列表、重命名、合并均限定在当前分区范围内",
        ),
    },

    "0.2.2": {
        "新增": (
            "已完成任务置底排序：DONE 任务自动排到列表底部，设置中可关闭",
            "双击编辑对话框：快速编辑 Markdown 内容，实时解析预览",
        ),
        "优化": (
            "双击编辑 Markdown 格式对齐右侧编辑面板规范",
            "预览增强：新增优先级和截止时刻显示",
            "中文按钮：对话框确定/取消按钮中文化",
        ),
        "修复": (
            "TaskDialog NameError：修复 TaskStatus 未导入导致崩溃",
            "raw_md 规范化：双击编辑保存时统一输出格式",
        ),
    },
    "0.2.1": {
        "新增": (
            "Linux 版本: 提供 <code>linux.tar.gz</code> 便携包",
        ),
    },

    "0.2.0": {
        "新增": (
            "状态下拉框即时刷新进度：切换至已完成→100，切回进行中→80",
        ),
        "优化": (
            "截止时间默认值对齐快速计算 23:59，创建任务预填当天日期",
            "快速计算标签：任务类型→时间粒度，临时→天",
        ),
        "修复": (
            "进度 100% 因列宽不足显示为 00",
            "多条状态→已完成路径遗漏进度=100 自动设定",
            "批量状态变更缺失 completed_at 和进度同步",
        ),
    },
    "0.1.2.4": {
        "修复": (
            "速览栏排除已完成已归档而非全部已完成",
            "阿里云盘更新检测支持 4 段版本号匹配",
        ),
    },
    "0.1.2.3": {
        "新增": (
            "关于对话框展示升级内容与下载渠道，更新结果内联反馈",
        ),
        "优化": (
            "提醒信息融入速览栏与进度栏被动展示，时间粒度细化至分钟",
            "欢迎页 Banner 动态适配分区状态",
            "更新检查优先阿里云盘",
        ),
        "修复": (
            "Banner 背景文字可读性",
            "启动遮罩期间鼠标转圈",
        ),
    },
    "0.1.2.2": {
        "新增": (
            "安装程序支持简体中文界面",
        ),
        "修复": (
            "安装程序中文乱码问题",
        ),
    },
    "0.1.2.1": {
        "新增": (
            "关于对话框检查更新与阿里云盘下载渠道",
            "联系方式与反馈渠道",
        ),
        "优化": (
            "关于对话框重新布局",
            "版本号统一为 4 位格式",
        ),
        "修复": (
            "进度栏时段筛选数据不一致",
            "进度栏与活动报告计数不匹配",
        ),
    },
}
