"""Version data — single point of truth updated by the release process.

This file contains *only* the version string and release highlights.
It is regenerated by ``generate_db.bat`` during release — do not edit
the data here by hand; instead update ``CHANGELOG.md`` and run the
release script.

Usage (always import via the public ``src.version`` module)::

    from src.version import __version__, get_release_highlights

"""

from __future__ import annotations

__version__ = "0.2.7"

# ------------------------------------------------------------------
# Release highlights — user-facing feature summaries per version
# ------------------------------------------------------------------

_RELEASE_HIGHLIGHTS: dict[str, dict[str, tuple[str, ...]]] = {
    "0.2.7": {
        "新增": (
            "CLI 命令行通道: <code>tadado-cli</code>（14 个命令：list/today/activity/add/edit/done/log/rm/tags/partitions/archive/recurrence/reminder/export/report）；GUI 运行时命令经本地管道转发给运行中实例（单一写者 + 实例身份校验），未运行时 headless 独立执行；JSON 输出 + <code>--format human</code>",
            "Claude Code skill: 自然语言管理任务（会话上下文/自动消歧/快捷计算六预设推断/安全分级确认），内置今日摘要/快速添加/批量添加/周报/月报工作流",
            "**周报 / 月报摘要**（<code>report</code> 命令 + skill 工作流）：分区优先、任务标签分组、本周工作内容 + 下周计划、无进展标注与优先排列，输出可直接粘贴进汇报",
            "AI 助手托盘入口: 一键启动专属 Claude Code / Codex 会话（自动续接上次会话、专用工作区、TADADO_EXE/TADADO_PARTITION 注入）；上下文超 80% 提醒 /compact",
            "补齐导入/导出服务模块: 新增 <code>md_exporter.py</code> / <code>md_importer.py</code>（修复任务视图导入/导出按钮点击即 ImportError 的潜伏问题）",
            "活动时间线只读展示: 双击任务编辑对话框内嵌与主界面同款样式的时间线，无记录自动隐藏",
            "skill 管理入口: 设置 → AI 助手页签，随附 skill（含版本号）为唯一权威源，可编辑并同步分发到 Claude/Codex",
        ),
        "优化": (
            "暖灰视觉重构: 设计令牌全面重标（暖灰阶文字对比度达标、暖调靛青强调色），卡片分层软阴影、圆角/字阶/焦点态统一；热力图四套配色重标（空单元格统一暖纸色、渐变锚定语义色）；深色主题暖灰化",
            "设置对话框页签化: 常规 / AI 助手 / 归档与分区 / 关于（帮助文档并入关于页，浏览器打开）",
            "关于页重构: 左侧品牌栏 + 分组行链接；版本更新记录浏览器打开（左侧可收起目录 + 版本标题锚点）",
            "热力图显示设置就地化: 配色方案与起始年份移至热力图导航栏（🏠 旁），即改即生效；统计指标移至热力图下方右侧",
            "Excel 导出下沉: 批量导出逻辑从 UI 控制器抽到 <code>services/task_exporter.py</code>，GUI 与 CLI 共用",
            "字体平台适配: Windows 使用系统字体；Linux 先探测系统 CJK/Emoji 字体，缺失才加载内置",
        ),
        "修复": (
            "关键词搜索计数: <code>repository.count()</code> FTS 分支修正为 <code>rowid IN</code> + LIKE 兜底，中文关键词搜索总数不再恒为 0",
            "配置默认值污染: <code>_deep_merge</code> 深拷贝修复，<code>set()</code> 不再污染全局 DEFAULT_CONFIG",
            "主题切换残留: Markdown 编辑器打开时切换主题不再残留旧主题背景；托盘菜单 aboutToShow 重建导致的点击无反应",
            "默认分区误跳: 任何配置变更不再触发跳回默认分区（仅默认分区值真正变化时切换）",
            "**管道可靠性**（Windows 命名管道）：服务端写完响应等客户端先断、客户端写完立即读、read_raw 收到首块即返回，修复响应丢失与互相等待",
        ),
    },
}
