"""Public version API — re-exports data from ``_version_data``.

The canonical version and release highlights live in ``_version_data.py``
(regenerated by ``generate_db.bat``).  This module provides the stable
public API that all application code imports from.

Usage::

    from src.version import __version__, get_version_display

"""

from __future__ import annotations

from ._version_data import __version__, _RELEASE_HIGHLIGHTS  # noqa: F401


def get_version() -> str:
    """Return the raw semver string, e.g. ``"0.1.2.1"``."""
    return __version__


def get_version_display() -> str:
    """Return the user-facing version string, e.g. ``"v0.1.2.1"``."""
    return f"v{__version__}"


def parse_version(version_str: str) -> tuple[int, ...]:
    """Parse a version string like ``"v1.2.3"`` or ``"1.2.3.1"`` into a
    variable-length tuple. 3-digit versions are padded to 4 for comparison."""
    clean = version_str.lstrip("v").strip()
    parts = clean.split(".")
    if len(parts) < 3 or len(parts) > 4:
        raise ValueError(f"Invalid version format: {version_str!r}")
    # Pad 3-digit → 4 for comparison: "0.1.0" → (0,1,0,0)
    while len(parts) < 4:
        parts.append("0")
    return tuple(int(p) for p in parts)  # type: ignore[return-value]


def get_release_highlights(version: str | None = None) -> dict[str, tuple[str, ...]] | None:
    """Return categorized feature highlights for *version*, or ``None``.

    Returns a dict like ``{"新增": (...), "优化": (...), "修复": (...)}``.
    When *version* is omitted, the current ``__version__`` is used.
    """
    v = version or __version__
    return _RELEASE_HIGHLIGHTS.get(v)
