<#
Tadado Windows Release Script — build + package
Usage: .\release.ps1   (version is read from src/version.py)
#>

$ErrorActionPreference = "Stop"
$Repo = "HananxR/Tadado"

# Run from project root regardless of where this script lives
Push-Location (Split-Path $PSScriptRoot -Parent)

# Read version set by generate_db.bat
$VerNum = (Select-String -Path src\_version_data.py -Pattern '__version__\s*=\s*"([^"]*)"').Matches.Groups[1].Value
$Tag = "v$VerNum"

# ===================================================================
# Step 1: Find Inno Setup
# ===================================================================
Write-Host "`n=== Step 1: Find Inno Setup ===" -ForegroundColor Cyan

$Iscc = $null
$IsccPaths = @(
    "$env:ProgramFiles\Inno Setup 7\ISCC.exe"
    "${env:ProgramFiles(x86)}\Inno Setup 7\ISCC.exe"
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
    (Get-Command iscc.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source)
)
foreach ($p in $IsccPaths) {
    if ($p -and (Test-Path $p)) { $Iscc = $p; Write-Host "Found: $Iscc" -ForegroundColor Green; break }
}
if (-not $Iscc) {
    Write-Host "Inno Setup not found — will skip EXE installer" -ForegroundColor Yellow
    Write-Host "Download: https://jrsoftware.org/isdl.php" -ForegroundColor Yellow
}

# ===================================================================
# Step 2: Build (version + DB already handled by generate_db.bat)
# ===================================================================
Write-Host "`n=== Step 2: Build ===" -ForegroundColor Cyan

# 清理构建目录——目录可能被资源管理器/杀毒/上次 ISCC 占用，
# 失败时等待重试，仍失败则用 robocopy /MIR 空目录清空内容兜底。
function Clear-Dir([string]$Path) {
    if (-not (Test-Path $Path)) { return }
    try { Remove-Item $Path -Recurse -Force -ErrorAction Stop }
    catch {
        Write-Host "[WARN] $Path is locked, retrying in 3s..." -ForegroundColor Yellow
        Start-Sleep -Seconds 3
        try { Remove-Item $Path -Recurse -Force -ErrorAction Stop }
        catch {
            $Empty = Join-Path $env:TEMP ("tadado_empty_" + [guid]::NewGuid())
            $null = New-Item -ItemType Directory -Path $Empty
            robocopy $Empty $Path /MIR /NFL /NDL /NJH /NJS | Out-Null
            Remove-Item $Empty -Recurse -Force
            if (Test-Path $Path) {
                Write-Error "Cannot clear $Path — close Explorer windows, antivirus scans, or running Tadado processes using it, then retry."
                exit 1
            }
        }
    }
    Write-Host "[OK] Cleaned $Path"
}

Clear-Dir "build\windows"
Clear-Dir "dist\windows"

# Check package DB (generated by generate_db.bat)
if (-not (Test-Path resources\tadado.data)) {
    Write-Error "resources\tadado.data not found. Run: pack_scripts\generate_db.bat vX.Y.Z"
    exit 1
}
if (-not (Test-Path resources\config.json)) {
    Write-Error "resources\config.json not found."
    exit 1
}
Write-Host "[OK] Package resources ready"

# Clean runtime logs — must NOT be bundled into the release package
if (Test-Path resources\loginfo) { Remove-Item resources\loginfo\* -Force -ErrorAction SilentlyContinue }
Write-Host "[OK] Cleaned resources\loginfo\"

# 同步 CHANGELOG 副本（打包内版本记录页面用）+ 重写双 exe spec（防单 exe 覆盖）
Copy-Item CHANGELOG.md resources\help\CHANGELOG.md -Force
uv run python scripts\write_dual_spec.py
if ($LASTEXITCODE -ne 0) { throw "write_dual_spec failed" }

try {
    uv run pyinstaller Tadado.spec --clean --workpath=build\windows --distpath=dist\windows
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller failed" }
} catch {
    throw
}
Write-Host "Build OK: dist\windows\Tadado\ (Tadado.exe + tadado-cli.exe)" -ForegroundColor Green

# ===================================================================
# Step 3: Package
# ===================================================================
Write-Host "`n=== Step 3: Package ===" -ForegroundColor Cyan

$null = New-Item -ItemType Directory -Force -Path dist\windows

$PortableZip = "dist\windows\Tadado_${Tag}_portable.zip"
# 便携包剔除内置字体（Windows 用系统字体，-27MB）
$PortableStage = Join-Path $env:TEMP "tadado_portable_stage"
if (Test-Path $PortableStage) { Remove-Item $PortableStage -Recurse -Force }
$null = New-Item -ItemType Directory -Force -Path $PortableStage
robocopy dist\windows\Tadado $PortableStage /E /XF "NotoSansCJKsc-Regular.otf" "NotoColorEmoji.ttf" /NFL /NDL /NJH /NJS | Out-Null
Compress-Archive -Path "$PortableStage\*" -DestinationPath $PortableZip -Force
Remove-Item $PortableStage -Recurse -Force
Write-Host "Portable: $PortableZip ($([math]::Round((Get-Item $PortableZip).Length/1MB, 1)) MB, fonts excluded)" -ForegroundColor Green

$InstallerExe = $null
if ($Iscc) {
    $issContent = [System.IO.File]::ReadAllText((Resolve-Path pack_scripts\installer.iss).Path, [System.Text.Encoding]::UTF8)
    $issContent = $issContent -replace '#define MyAppVersion ".*"', "#define MyAppVersion ""$VerNum"""
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText((Resolve-Path pack_scripts\installer.iss).Path, $issContent, $utf8Bom)
    cmd /c "`"$Iscc`" pack_scripts\installer.iss"
    if ($LASTEXITCODE -eq 0) {
        $InstallerExe = "dist\windows\Tadado_setup_v${VerNum}.exe"
        Write-Host "Installer: $InstallerExe ($([math]::Round((Get-Item $InstallerExe).Length/1MB, 1)) MB)" -ForegroundColor Green
    } else { Write-Host "Inno Setup compile failed" -ForegroundColor Red }
}

# Source code archive is auto-generated by GitHub — no need to upload our own
Write-Host "Source archive: GitHub will auto-generate Source code (zip/tar.gz)" -ForegroundColor Cyan

# ===================================================================
# Step 4: Git tag + push
# ===================================================================
Write-Host "`n=== Step 4: Git tag + push ===" -ForegroundColor Cyan

# Always move tag to current HEAD — ensures release points to this exact build
git tag -f $Tag HEAD
Write-Host "Tag $Tag -> HEAD ($(git rev-parse --short HEAD))" -ForegroundColor Green

# Push commits and tag
git push origin HEAD:main
git push -f origin $Tag
Write-Host "Pushed to origin: main + $Tag" -ForegroundColor Green

# ===================================================================
# Step 5: Upload to GitHub Release
# ===================================================================
Write-Host "`n=== Step 5: Upload release ===" -ForegroundColor Cyan
Write-Host "Open this URL and drag the files in:" -ForegroundColor Magenta
Write-Host ""
Write-Host "  https://github.com/$Repo/releases/new?tag=$Tag&title=Tadado%20$Tag" -ForegroundColor White
Write-Host ""
Write-Host "Files to upload:" -ForegroundColor Cyan
Write-Host "  $PortableZip" -ForegroundColor White
if ($InstallerExe) { Write-Host "  $InstallerExe" -ForegroundColor White }
Write-Host ""
Write-Host "Then click 'Publish release'." -ForegroundColor Cyan

Start-Process "https://github.com/$Repo/releases/new?tag=$Tag&title=Tadado%20$Tag"

# Cloud drive upload is handled separately — run upload_aliyun.ps1 when ready:
#   .\upload_aliyun.ps1 $Tag

Write-Host "`n=== Done ===" -ForegroundColor Cyan
