#!/usr/bin/env bash
# =============================================================================
# Tadado Linux Release Script — build + package
# Usage: ./release.sh   (version is read from src/version.py)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

# Read version set by generate_db.bat
VER_NUM=$(grep -oP '__version__\s*=\s*"\K[^"]*' src/_version_data.py)
TAG="v$VER_NUM"
REPO="HananxR/Tadado"

# NOTE: Make sure CHANGELOG.md is already updated before running this script.
# The commit happens in Step 5 after a successful build.

# ---------------------------------------------------------------------------
# 1. Check environment
# ---------------------------------------------------------------------------
echo ""
echo "=== Step 1: Check environment ==="

if ! command -v uv &> /dev/null; then
    echo "ERROR: uv is not installed. Install it first: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

# Reject Windows uv.exe picked up via WSL PATH interop (causes cpython-windows-x86_64)
UV_PATH="$(command -v uv)"
if [[ "$UV_PATH" == /mnt/* ]]; then
    echo "ERROR: Detected Windows uv (${UV_PATH}) via WSL PATH interop."
    echo "  This causes 'ModuleNotFoundError: No module named encodings' later."
    echo "  Install Linux-native uv: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi
echo "[OK] uv found: $(uv --version)"

# Activate Linux venv (independent from Windows .venv)
if [ ! -d .venv-linux ]; then
    uv venv .venv-linux --python 3.10
fi
source .venv-linux/bin/activate
uv pip install -e . pyinstaller
echo "[OK] Linux venv ready: $(python --version)"

if ! pyinstaller --version &> /dev/null; then
    echo "ERROR: pyinstaller not found after pip install. Check pyproject.toml."
    exit 1
fi
echo "[OK] pyinstaller found: $(pyinstaller --version)"

# Ensure bundled fonts exist
MISSING_FONTS=""
if [ ! -f resources/fonts/NotoSansCJKsc-Regular.otf ]; then
    MISSING_FONTS="$MISSING_FONTS  NotoSansCJKsc-Regular.otf (CJK)\n"
fi
if [ ! -f resources/fonts/NotoColorEmoji.ttf ]; then
    MISSING_FONTS="$MISSING_FONTS  NotoColorEmoji.ttf (Emoji)\n"
fi
if [ -n "$MISSING_FONTS" ]; then
    echo "ERROR: Missing bundled fonts:\n$MISSING_FONTS"
    echo "  See resources/fonts/README for download instructions."
    exit 1
fi
echo "[OK] Bundled fonts: NotoSansCJKsc-Regular + NotoColorEmoji"

# ---------------------------------------------------------------------------
# 2. Build (version + DB already handled by generate_db.bat)
# ---------------------------------------------------------------------------
echo ""
echo "=== Step 2: Build ==="

# ---- Clean only Linux platform artifacts (never touch dist/windows/) ----
rm -rf build/linux dist/linux
echo "[OK] Cleaned build/linux/ and dist/linux/"

    # ---- Check package DB (generated by generate_db.bat) ----
    if [ ! -f resources/tadado.data ]; then
        echo "ERROR: resources/tadado.data not found."
        echo "  Run: pack_scripts/generate_db.bat vX.Y.Z"
        exit 1
    fi
    if [ ! -f resources/config.json ]; then
        echo "ERROR: resources/config.json not found."
        exit 1
    fi
    echo "[OK] Package resources ready"

# Clean runtime logs — must NOT be bundled into the release package
rm -rf resources/loginfo/*
echo "[OK] Cleaned resources/loginfo/"

# ---- Sync CHANGELOG + rewrite dual-exe spec (same as Windows release) ----
cp CHANGELOG.md resources/help/CHANGELOG.md
python scripts/write_dual_spec.py

# ---- PyInstaller (output confined to dist/linux/, spec-driven dual exe) ----
echo ""
echo "--- Running PyInstaller ---"
# NOTE: colon `:` is the path separator on Linux (Windows uses semicolon `;`)
# NOTE: spec datas use tuple form — PyInstaller normalizes per platform
# NOTE: --workpath + --distpath isolate ALL build artifacts per platform
pyinstaller \
    Tadado.spec \
    --clean \
    --workpath=build/linux \
    --distpath=dist/linux

echo "[OK] Build complete: dist/linux/Tadado/ (Tadado + tadado-cli)"
echo "[OK] Restored dev database files"

# ---------------------------------------------------------------------------
# 4. Package
# ---------------------------------------------------------------------------
echo ""
echo "=== Step 3: Package ==="

PORTABLE_TGZ="dist/linux/Tadado_${TAG}_linux.tar.gz"
tar -czf "$PORTABLE_TGZ" -C dist/linux Tadado/
echo "[OK] Portable: $PORTABLE_TGZ ($(du -h "$PORTABLE_TGZ" | cut -f1))"

# Source code archive is auto-generated by GitHub — no need to upload our own
echo "[OK] Source archive: GitHub will auto-generate Source code (zip/tar.gz)"

# Git tag + push is handled by release.ps1 (Windows). Skip on Linux to avoid conflicts.

# ---------------------------------------------------------------------------
# 5. Upload reminder
# ---------------------------------------------------------------------------
echo ""
echo "=== Step 4: Upload release ==="
echo "Open this URL and drag the files in:"
echo ""
echo "  https://github.com/$REPO/releases/new?tag=$TAG&title=Tadado%20$TAG"
echo ""
echo "Files to upload:"
echo "  $PORTABLE_TGZ"
echo ""
echo "========"
echo "=== Done ==="
echo "========"
