<#
Tadado Aliyun Drive Upload Script
Upload already-built dist artifacts to Aliyun Drive share folder.

Usage:
    .\upload_aliyun.ps1 v0.1.0           # upload for a specific tag
    .\upload_aliyun.ps1 v0.1.0 -SkipZip  # skip portable ZIP, only upload installer

Prerequisites:
    aliyunpan CLI — https://github.com/tickstep/aliyunpan
    Install and login first:
        aliyunpan.exe login
#>
param(
    [switch]$SkipZip,
    [switch]$SkipInstaller
)

$ErrorActionPreference = "Stop"
Push-Location (Split-Path $PSScriptRoot -Parent)

$VerNum = (Select-String -Path src\_version_data.py -Pattern '__version__\s*=\s*"([^"]*)"').Matches.Groups[1].Value
$Version = "v$VerNum"

# ------------------------------------------------------------------
# Helper: locate aliyunpan CLI across PATH + known install dirs
# ------------------------------------------------------------------
function _FindAliyunpanCLI {
    # 1) Check PATH
    $cmd = Get-Command aliyunpan.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
    if ($cmd) { Write-Host "Found in PATH: $cmd" -ForegroundColor Green; return $cmd }

    # 2) Scan known directories
    $candidates = @(
        "$env:LOCALAPPDATA\aliyunpan\aliyunpan.exe",
        "$env:ProgramFiles\aliyunpan\aliyunpan.exe",
        "${env:ProgramFiles(x86)}\aliyunpan\aliyunpan.exe"
    )
    # Also scan D:\aliyunpan-* folders (versioned installs)
    try {
        $matches = Get-ChildItem "D:\aliyunpan-*" -Directory -ErrorAction SilentlyContinue
        foreach ($d in $matches) {
            $candidates += Join-Path $d.FullName "aliyunpan.exe"
        }
    } catch {}
    try {
        $matches = Get-ChildItem "$env:USERPROFILE\aliyunpan-*" -Directory -ErrorAction SilentlyContinue
        foreach ($d in $matches) {
            $candidates += Join-Path $d.FullName "aliyunpan.exe"
        }
    } catch {}

    foreach ($p in $candidates) {
        if (Test-Path $p) {
            Write-Host "Found: $p" -ForegroundColor Green
            return $p
        }
    }
    return $null
}

# ------------------------------------------------------------------
# Helper: ensure aliyunpan targets the Resource drive (资源库),
# not the Backup drive (备份盘). Modifies aliyunpan_config.json.
# ------------------------------------------------------------------
function _SetActiveDriveToResource($CliPath) {
    $configDir = Split-Path $CliPath -Parent
    $configFile = Join-Path $configDir "aliyunpan_config.json"
    if (-not (Test-Path $configFile)) { return $false }

    $config = Get-Content $configFile -Raw -Encoding UTF8 | ConvertFrom-Json
    $resourceDrive = $config.userList[0].driveList | Where-Object { $_.driveTag -eq "Resource" }
    if (-not $resourceDrive) {
        Write-Host "WARNING: no Resource drive found in config" -ForegroundColor Yellow
        return $false
    }
    $currentActive = $config.userList[0].activeDriveId
    if ($currentActive -eq $resourceDrive.driveId) {
        return $true  # already correct
    }
    $config.userList[0].activeDriveId = $resourceDrive.driveId
    $config | ConvertTo-Json -Depth 10 | Set-Content $configFile -Encoding UTF8
    Write-Host "Switched active drive -> $($resourceDrive.driveName) ($($resourceDrive.driveId))" -ForegroundColor Green
    return $true
}

$AliDriveShare = "https://www.alipan.com/s/E2FBppaMPZj"
$RemoteDir = "/Tadado"

# ===================================================================
# Find artifacts
# ===================================================================
Write-Host "=== Scan dist/ for artifacts ===" -ForegroundColor Cyan

$PortableZip  = "dist\windows\Tadado_${Version}_portable.zip"
$InstallerExe = "dist\windows\Tadado_setup_v${VerNum}.exe"
$LinuxTarball = "dist\linux\Tadado_${Version}_linux.tar.gz"

$Files = @()
if (-not $SkipZip -and (Test-Path $PortableZip)) {
    $Files += $PortableZip
    Write-Host "  Found: $PortableZip ($([math]::Round((Get-Item $PortableZip).Length/1MB, 1)) MB)" -ForegroundColor Green
} elseif (-not $SkipZip) {
    Write-Host "  NOT FOUND: $PortableZip" -ForegroundColor Yellow
}

if (-not $SkipInstaller -and (Test-Path $InstallerExe)) {
    $Files += $InstallerExe
    Write-Host "  Found: $InstallerExe ($([math]::Round((Get-Item $InstallerExe).Length/1MB, 1)) MB)" -ForegroundColor Green
} elseif (-not $SkipInstaller) {
    Write-Host "  NOT FOUND: $InstallerExe — build installer first with Inno Setup" -ForegroundColor Yellow
}

if (Test-Path $LinuxTarball) {
    $Files += $LinuxTarball
    Write-Host "  Found: $LinuxTarball ($([math]::Round((Get-Item $LinuxTarball).Length/1MB, 1)) MB)" -ForegroundColor Green
} else {
    Write-Host "  NOT FOUND: $LinuxTarball — build with release.sh first" -ForegroundColor Yellow
}

# Source archive is auto-generated by GitHub — skip

if ($Files.Count -eq 0) {
    Write-Host "No files to upload. Run build.bat / release.ps1 first." -ForegroundColor Red
    exit 1
}

# ===================================================================
# Find aliyunpan CLI
# ===================================================================
Write-Host "`n=== Check aliyunpan CLI ===" -ForegroundColor Cyan

$AliyunpanCLI = _FindAliyunpanCLI

if (-not $AliyunpanCLI) {
    Write-Host "aliyunpan CLI not found." -ForegroundColor Red
    Write-Host "Download: https://github.com/tickstep/aliyunpan/releases" -ForegroundColor Yellow
    Write-Host "Install: extract to D:\\aliyunpan and add to PATH, or run:  aliyunpan.exe login" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Opening share link for manual upload..." -ForegroundColor Magenta
    Write-Host "  $AliDriveShare" -ForegroundColor White
    Write-Host ""
    Write-Host "Files to upload:" -ForegroundColor Cyan
    foreach ($f in $Files) { Write-Host "  $f" -ForegroundColor White }
    Start-Process $AliDriveShare
    exit 0
}

Write-Host "Found: $AliyunpanCLI" -ForegroundColor Green

# Ensure we upload to 资源库 (Resource drive), not 备份盘
_SetActiveDriveToResource $AliyunpanCLI | Out-Null

# ===================================================================
# Upload
# ===================================================================
Write-Host "`n=== Uploading to Aliyun Drive ===" -ForegroundColor Cyan
Write-Host "Remote dir: $RemoteDir" -ForegroundColor White
Write-Host "Share link: $AliDriveShare" -ForegroundColor White
Write-Host ""

$Failed = @()
foreach ($f in $Files) {
    $remoteName = Split-Path $f -Leaf
    $remotePath = "$RemoteDir/$remoteName"
    # Remove existing file so we don't get (1) suffixed duplicates
    Write-Host "Checking $remotePath ..." -ForegroundColor Cyan
    & $AliyunpanCLI rm $remotePath 2>&1 | Out-Null
    Write-Host "Uploading $f ..." -ForegroundColor Cyan
    & $AliyunpanCLI upload $f $RemoteDir
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  FAILED — check aliyunpan login status (run: aliyunpan.exe login)" -ForegroundColor Red
        $Failed += $f
    } else {
        Write-Host "  OK" -ForegroundColor Green
    }
}

# ===================================================================
# Summary
# ===================================================================
Write-Host ""
if ($Failed.Count -eq 0) {
    Write-Host "=== All files uploaded successfully ===" -ForegroundColor Green
} else {
    Write-Host "=== ${Failed.Count} file(s) failed ===" -ForegroundColor Yellow
    foreach ($f in $Failed) { Write-Host "  FAILED: $f" -ForegroundColor Red }
}

Write-Host ""
Write-Host "Verify at: $AliDriveShare" -ForegroundColor Magenta
Start-Process $AliDriveShare
